services:
  keycloak:
    container_name: keycloak_demo
    image: quay.io/keycloak/keycloak:26.4.7
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: user_admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    command:
      - 'start-dev'

volumes:
  keycloak_data: